(function(){
  'use strict';
  window.H38_ECOSYSTEM = Object.freeze({
    release: 'complete-ecosystem-live-launch-2026-07-11',
    divisions: [
      {id:'solutions',name:'Highway 38 Solutions',purpose:'Done-for-you and guided planning, workflow, layout, and decision-support services.',href:'services.html'},
      {id:'tools',name:'Highway 38 Tools',purpose:'Free calculators, checklists, scorecards, and future verified DIY products.',href:'free-tools.html'},
      {id:'business-os',name:'Highway 38 Business OS',purpose:'Transferable owner-controlled operating system, configuration, and support.',href:'business-os.html'},
      {id:'supply',name:'Highway 38 Supply Co.',purpose:'Future physical products and mixed product packages. No public checkout until fulfillment is verified.',href:'resources.html#supply'}
    ],
    addOns: [
      {id:'H38-ADD001',name:'Extra area, room, machine, or workflow',price:125,compatible:['H38-P002','H38-P003','H38-P004','H38-P007','H38-P010'],deliverable:'One additional bounded area or workflow added to the approved scope.',turnaroundEffect:'Adds 1–2 business days.',revisionRule:'Uses the parent product revision allowance.',payment:'Paid before expanded work begins.',status:'OWNER_REVIEW'},
      {id:'H38-ADD002',name:'Additional layout option',price:149,compatible:['H38-P002','H38-P003','H38-P004'],deliverable:'One additional concept direction using the same verified inputs.',turnaroundEffect:'Adds 2 business days.',revisionRule:'One comparison clarification; no merged third option.',payment:'Paid before alternate layout work begins.',status:'OWNER_REVIEW'},
      {id:'H38-ADD003',name:'CAD redline',price:175,compatible:['H38-P002','H38-P003','H38-P011','H38-P012'],deliverable:'One annotated redline over a customer-supplied drawing.',turnaroundEffect:'Adds 1–2 business days.',revisionRule:'One factual correction pass.',payment:'Paid before production.',status:'OWNER_REVIEW'},
      {id:'H38-ADD004',name:'Material-list grouping',price:125,compatible:['H38-P003','H38-P004'],deliverable:'Grouped purchasing categories and decision checkpoints; quantities remain field-verified.',turnaroundEffect:'Adds 1 business day.',revisionRule:'One clarification pass.',payment:'Paid before production.',status:'OWNER_REVIEW'},
      {id:'H38-ADD005',name:'3D concept view',price:299,compatible:['H38-P002','H38-P003','H38-P011','H38-P012'],deliverable:'One non-engineering visual concept view.',turnaroundEffect:'Adds 3–4 business days.',revisionRule:'One bounded camera/material correction.',payment:'Paid before production.',status:'OWNER_REVIEW'},
      {id:'H38-ADD006',name:'Video walkthrough',price:149,compatible:['H38-P002','H38-P003','H38-P004','H38-P005','H38-P008'],deliverable:'Up to 15 minutes of recorded explanation of the approved deliverable.',turnaroundEffect:'Adds 1 business day.',revisionRule:'Replacement only for factual error.',payment:'Paid before recording.',status:'OWNER_REVIEW'},
      {id:'H38-ADD007',name:'Vendor RFQ export',price:199,compatible:['H38-P010','H38-P011','H38-P012','H38-P013','H38-P014','H38-P015'],deliverable:'Vendor-ready requirements table exported from the approved decision packet.',turnaroundEffect:'Adds 2 business days.',revisionRule:'One factual correction pass.',payment:'Paid before export.',status:'OWNER_REVIEW'},
      {id:'H38-ADD008',name:'Quote comparison',price:149,compatible:['H38-P010','H38-P011','H38-P012','H38-P013','H38-P014','H38-P015'],deliverable:'Side-by-side comparison of up to three customer-supplied vendor quotes.',turnaroundEffect:'Adds 2 business days.',revisionRule:'One correction pass after vendor clarification.',payment:'Paid before analysis.',status:'OWNER_REVIEW'},
      {id:'H38-ADD009',name:'Additional revision',price:99,compatible:['ALL'],deliverable:'One bounded revision within the original goal and inputs.',turnaroundEffect:'Adds 1–3 business days.',revisionRule:'Does not expand scope.',payment:'Paid before revision.',status:'OWNER_REVIEW'},
      {id:'H38-ADD010',name:'Rush turnaround',priceRule:'35% of base product price',compatible:['SELECTED'],deliverable:'Priority placement when capacity and input completeness permit.',turnaroundEffect:'Confirmed in writing before payment.',revisionRule:'Unchanged.',payment:'Paid before work begins.',status:'OWNER_REVIEW'},
      {id:'H38-ADD011',name:'Implementation check-in',price:125,compatible:['H38-P003','H38-P004','H38-P005','H38-P008','H38-P009'],deliverable:'One 45-minute owner-controlled implementation review plus action notes.',turnaroundEffect:'Scheduled within 10 business days.',revisionRule:'One factual correction to notes.',payment:'Paid before scheduling.',status:'OWNER_REVIEW'},
      {id:'H38-ADD012',name:'Editable source file',price:99,compatible:['SELECTED'],deliverable:'Editable source in the format stated in the quote when licensing permits.',turnaroundEffect:'No change.',revisionRule:'No support beyond opening instructions.',payment:'Paid before unrestricted delivery.',status:'OWNER_REVIEW'},
      {id:'H38-ADD013',name:'Additional output format',price:49,compatible:['ALL'],deliverable:'One additional approved export format.',turnaroundEffect:'Adds 1 business day.',revisionRule:'Replacement for export defect only.',payment:'Paid before export.',status:'OWNER_REVIEW'}
    ],
    contracts: [
      {id:'H38-C001',name:'Plan Care',price:149,period:'month',included:'One bounded plan clarification or update request per month.',response:'Acknowledgment within 2 business days.',rollover:'No rollover.',exclusions:'New projects, field verification, licensed work, and unlimited communication.',cancellation:'Cancel before next billing date; current month remains active.',status:'OWNER_REVIEW'},
      {id:'H38-C002',name:'Project Care',price:299,period:'month',included:'Two bounded project check-ins or document updates per month.',response:'Acknowledgment within 2 business days.',rollover:'One unused request may roll one month.',exclusions:'Site supervision, contractor management, and new deliverables.',cancellation:'Cancel before next billing date.',status:'OWNER_REVIEW'},
      {id:'H38-C003',name:'Business Systems Care',price:399,period:'month',included:'Two bounded workflow, template, tracker, or status-control requests per month.',response:'Acknowledgment within 1 business day.',rollover:'No rollover.',exclusions:'Custom software, bookkeeping, and unreviewed external sends.',cancellation:'Cancel before next billing date.',status:'OWNER_REVIEW'},
      {id:'H38-C004',name:'Shop Improvement Care',price:499,period:'month',included:'Two shop-flow or implementation review requests plus a monthly action summary.',response:'Acknowledgment within 2 business days.',rollover:'No rollover.',exclusions:'Safety certification, engineering, installation, and unlimited site review.',cancellation:'Cancel before next billing date.',status:'OWNER_REVIEW'},
      {id:'H38-C005',name:'Manufacturing Improvement Partner',price:995,period:'month',included:'One focused improvement cycle with data review, vendor questions, and decision notes.',response:'Acknowledgment within 1 business day.',rollover:'No rollover.',exclusions:'Engineering signoff, controls programming, guarding validation, and production guarantees.',cancellation:'30-day notice after initial 90-day term.',status:'OWNER_REVIEW'},
      {id:'H38-C006',name:'Business OS Care',price:249,period:'month',included:'Configuration support, release guidance, backup review, and two bounded support requests.',response:'Acknowledgment within 1 business day.',rollover:'No rollover.',exclusions:'Third-party subscription fees, custom modules, and unapproved external actions.',cancellation:'Cancel before next billing date.',status:'OWNER_REVIEW'}
    ],
    osTiers: [
      {id:'H38-OS001',name:'Core',setup:2500,includes:['Unified tasks','Customers and jobs','Owner approvals','Proof and error logs','Catalog controls','Backup and recovery'],status:'OWNER_REVIEW'},
      {id:'H38-OS002',name:'Operations',setup:5000,includes:['Core tier','Quotes and invoices','Payments and expenses','Communications','Customer portal configuration','Operating SOP package'],status:'OWNER_REVIEW'},
      {id:'H38-OS003',name:'Growth',setup:8500,includes:['Operations tier','Social and campaign controls','Website change control','Attribution reporting','Business Concept Builder','Growth dashboards'],status:'OWNER_REVIEW'},
      {id:'H38-OS004',name:'Control',setup:15000,includes:['Growth tier','Multi-business separation','White-label configuration','Release channels','Migration tooling','Advanced recovery and governance'],status:'OWNER_REVIEW'}
    ],
    proof: [
      {id:'H38-PROOF-001',title:'Blanking-feed automation planning',classification:'Anonymized reconstruction',domain:'Manufacturing and automation',summary:'A controlled reconstruction showing sequence definition, material handling, sensor logic, guarding questions, installation gates, and measurable production criteria without employer, vendor, part, or plant identifiers.',evidenceStatus:'Private source evidence requires owner privacy approval before any historical claim is upgraded.',related:['H38-P010','H38-P011']},
      {id:'H38-PROOF-002',title:'Robot-tended lathe workflow',classification:'Anonymized reconstruction',domain:'Manufacturing and automation',summary:'A public-safe reconstruction of part presentation, gripper and chuck interface questions, machine signals, probing, exception handling, queue control, and decision criteria.',evidenceStatus:'No proprietary drawings, programs, videos, or production data published.',related:['H38-P010','H38-P015']},
      {id:'H38-PROOF-003',title:'CNC and CAD/CAM standardization',classification:'Verified historical experience — public-safe summary',domain:'Machining and digital manufacturing',summary:'Experience implementing CNC programming standards, CAD/CAM workflows, posts, tool libraries, feeds and speeds, troubleshooting, quoting, and repeatable output controls across long-term manufacturing work.',evidenceStatus:'Public wording is intentionally non-quantified until PST and file evidence corroboration is complete.',related:['H38-P010','H38-P011']},
      {id:'H38-PROOF-004',title:'Garage flow and zone planning',classification:'Demonstration sample',domain:'Residential and shop planning',summary:'A 28×40 garage example showing protected vehicle lanes, workbench and tool zones, fixed-obstacle checks, missing measurements, and phased setup actions.',evidenceStatus:'Hypothetical demonstration; not presented as customer work.',related:['H38-P002','H38-P003','H38-P004']},
      {id:'H38-PROOF-005',title:'Small-business lead-to-job control',classification:'Demonstration sample',domain:'Business systems',summary:'A seven-status owner-controlled workflow connecting intake, missing information, quote review, scheduling, completion, and follow-up without automatic customer sends.',evidenceStatus:'Synthetic data only.',related:['H38-P005','H38-P007','H38-P008']},
      {id:'H38-PROOF-006',title:'Residential sequencing and planning experience',classification:'Historical experience — evidence review in progress',domain:'Residential projects',summary:'Experience planning remodeling, garages, kitchens, concrete, landscaping, materials, and construction sequence. Named project case studies remain private until photos and records pass privacy review.',evidenceStatus:'Named projects, addresses, family, and customer records are not published from this dataset.',related:['H38-P002','H38-P003']}
    ],
    providers: [
      {id:'gmail',feature:'Customer email, quote, invoice, and delivery sends',mode:'APPROVAL_GATED',status:'CODE_READY_CONNECTION_BLOCKED',blocker:'Authorize the production Gmail account and confirm approved sender identity in the bound Apps Script project.'},
      {id:'payments',feature:'Provider-hosted payment links, receipts, refunds, subscriptions',mode:'PROVIDER_HOSTED',status:'PROVIDER_SELECTION_BLOCKED',blocker:'Rick must select Stripe, Square, or PayPal and supply a production account/API connection. Raw card data will never enter the portal.'},
      {id:'metricool',feature:'Social scheduling and publication',mode:'APPROVAL_GATED',status:'CREDENTIAL_BLOCKED',blocker:'Connect or replace the Metricool account and verify each channel permission. Publication remains disabled until then.'},
      {id:'accounting',feature:'Accounting synchronization',mode:'CSV_READY',status:'CSV_LIVE_API_BLOCKED',blocker:'CSV export is ready. Select QuickBooks, Xero, Wave, or FreshBooks and authorize the chosen API for direct synchronization.'},
      {id:'customer-auth',feature:'Customer portal authentication and file access',mode:'CUSTOMER_ISOLATED',status:'AUTH_PROVIDER_BLOCKED',blocker:'Select and configure an authentication provider and customer-file authorization model before public customer portal activation.'},
      {id:'analytics',feature:'Lead attribution and conversion analytics',mode:'PRIVACY_MINIMIZED',status:'PROPERTY_ID_BLOCKED',blocker:'Provide the approved analytics property or measurement ID and consent requirements.'},
      {id:'social-accounts',feature:'Facebook, Instagram, LinkedIn, Google Business Profile, YouTube',mode:'OWNER_CONTROLLED',status:'ACCOUNT_ACCESS_BLOCKED',blocker:'Create or grant owner access to each approved channel, then verify profile, links, media, and publishing permissions.'}
    ]
  });
})();
