(function(){
  'use strict';
  const M=window.H38_TOOL_FORMULAS,$=id=>document.getElementById(id),num=id=>Number($(id)?.value||0);
  const fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:d}):'—',money=n=>Number.isFinite(n)?n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}):'—';
  const field=(id,label,value,opts='')=>`<div class="eco-field"><label for="${id}">${label}</label><input id="${id}" type="number" value="${value}" ${opts}></div>`;
  const tool=(id,tag,title,body,action,result,related='')=>`<article class="eco-card eco-tool" id="${id}"><div class="eco-meta"><span class="eco-chip">${tag}</span><span class="eco-chip eco-chip--ok">Live</span></div><h3>${title}</h3>${body}<button class="eco-button eco-button--primary" onclick="H38Tools.${action}()">Calculate</button><output id="${result}" class="eco-result">Enter values and calculate.</output>${related?`<p><a href="${related}">Related paid service</a></p>`:''}</article>`;
  function render(){const host=$('tool-library');if(!host)return;const quote=['Scope and part definition','Volumes and mix','Cycle-time basis','Quality and inspection','Tooling and fixtures','Controls and interfaces','Safety and guarding responsibilities','Installation and training','Acceptance criteria','Lead time and warranty','Commercial exclusions'];const shop=['Travel path','Daily-tool access','Active-job staging','Incoming work control','Material location','Finished-work exit','Visual status','Cleanup standard'];const robot=['Part presentation','Part variation','Cycle stability','Machine interface','Workholding repeatability','In-process checks','Exception handling','Safety concept','Maintenance ownership','Production volume'];const scoreFields=(items,prefix,kind)=>`<p>Rate each item from 1 to 5.</p><div class="eco-tool-grid">${items.map((x,i)=>`<div class="eco-field"><label for="${prefix}_${i}">${x}</label><select id="${prefix}_${i}" data-score="${kind}"><option>1</option><option>2</option><option selected>3</option><option>4</option><option>5</option></select></div>`).join('')}</div>`;
    host.innerHTML=[
      tool('machining-calculator','Manufacturing','Machining Quick Calculator',`<div class="eco-tool-grid">${field('m_sfm','Surface speed (SFM)',300,'min="0" step="any"')}${field('m_diameter','Tool diameter (in.)',.5,'min="0" step="any"')}${field('m_teeth','Cutting teeth',4,'min="0" step="1"')}${field('m_chip','Chip load (in./tooth)',.003,'min="0" step="0.0001"')}</div>`,'machining','m_result','start-request.html?product=H38-P010'),
      tool('automation-payback','ROI','Automation Payback Estimator',`<div class="eco-tool-grid">${field('a_cost','Total installed investment',100000,'min="0"')}${field('a_hours','Hours saved/week',40,'min="0"')}${field('a_rate','Loaded hourly value',45,'min="0"')}${field('a_weeks','Operating weeks/year',50,'min="0" max="52"')}${field('a_other','Other annual benefit',10000,'min="0"')}</div>`,'payback','a_result','start-request.html?product=H38-P010'),
      tool('bottleneck-cost','Shop flow','Shop Bottleneck Cost Calculator',`<div class="eco-tool-grid">${field('b_minutes','Lost minutes/day',45,'min="0"')}${field('b_days','Working days/year',240,'min="0"')}${field('b_rate','Loaded hourly cost',55,'min="0"')}${field('b_people','People affected',2,'min="1"')}</div>`,'bottleneck','b_result','start-request.html?product=H38-P004'),
      tool('bar-feed','Machining','Bar-Feed Production Calculator',`<div class="eco-tool-grid">${field('bf_bar','Bar length (in.)',144,'min="0"')}${field('bf_part','Part stock length (in.)',2,'min="0" step="any"')}${field('bf_remnant','Remnant/end loss (in.)',8,'min="0"')}${field('bf_kerf','Cutoff/facing allowance (in.)',.125,'min="0" step="any"')}${field('bf_cycle','Cycle time (sec.)',60,'min="0"')}${field('bf_hours','Run hours',8,'min="0"')}${field('bf_eff','Efficiency (%)',80,'min="0" max="100"')}</div>`,'barfeed','bf_result'),
      tool('press-feed','Press','Press-Feed Capacity Worksheet',`<div class="eco-tool-grid">${field('pf_spm','Strokes/minute',30,'min="0"')}${field('pf_pitch','Feed pitch (in.)',4,'min="0" step="any"')}${field('pf_hours','Scheduled hours',8,'min="0"')}${field('pf_eff','Efficiency (%)',75,'min="0" max="100"')}${field('pf_coil','Optional usable coil length (ft.)',3000,'min="0"')}</div>`,'pressfeed','pf_result'),
      `<article class="eco-card eco-tool"><div class="eco-meta"><span class="eco-chip">Vendor RFQ</span><span class="eco-chip eco-chip--ok">Live</span></div><h3>Vendor Quote Completeness Checklist</h3><div class="eco-form">${quote.map(x=>`<label><input type="checkbox" data-quote-check value="${x}"> ${x}</label>`).join('')}</div><div class="eco-actions"><button class="eco-button eco-button--primary" onclick="H38Tools.quote()">Score completeness</button><button class="eco-button eco-button--outline" onclick="H38Tools.downloadQuote()">Download CSV</button></div><output id="q_result" class="eco-result">Mark the categories included in the quote.</output></article>`,
      tool('shop-flow-score','Scorecard','Shop Flow Scorecard',scoreFields(shop,'sf','shop-flow'),'shopFlow','sf_result','start-request.html?product=H38-P004'),
      tool('robot-readiness','Automation scorecard','Robot-Tending Readiness Score',scoreFields(robot,'rr','robot'),'robot','rr_result','start-request.html?product=H38-P015')
    ].join('');}
  const set=(id,html,kind='')=>{const out=$(id);if(out){out.className='eco-result '+kind;out.innerHTML=html;}};
  function track(name){window.h38AnalyticsQueue=window.h38AnalyticsQueue||[];window.h38AnalyticsQueue.push({event:'tool_calculate',tool:name,timestamp:new Date().toISOString()});}
  function machining(){try{const r=M.machining({sfm:num('m_sfm'),diameter:num('m_diameter'),teeth:num('m_teeth'),chip:num('m_chip')});set('m_result',`<strong>${fmt(r.rpm,0)} RPM</strong><br>${fmt(r.feed,2)} inches/minute programmed feed.<p class="eco-disclaimer">Starting estimate only. Confirm toolmaker, material, machine, workholding, coolant, and safety limits.</p>`,'eco-safe');track('machining');}catch(e){set('m_result',e.message);}}
  function payback(){try{const r=M.payback({cost:num('a_cost'),hoursPerWeek:num('a_hours'),loadedRate:num('a_rate'),weeksPerYear:num('a_weeks'),otherAnnual:num('a_other')});set('a_result',`<strong>${fmt(r.paybackMonths,1)} month simple payback</strong><br>Estimated annual benefit: ${money(r.annualBenefit)}.<br>First-year simple ROI: ${fmt(r.firstYearRoiPercent,1)}%.<p class="eco-disclaimer">Validate uptime, labor redeployment, scrap, maintenance, financing, tax, and implementation risk.</p>`,'eco-safe');track('payback');}catch(e){set('a_result',e.message);}}
  function bottleneck(){try{const r=M.bottleneck({minutesPerDay:num('b_minutes'),workingDays:num('b_days'),loadedRate:num('b_rate'),people:num('b_people')});set('b_result',`<strong>${fmt(r.annualHours,0)} hours/year exposed</strong><br>Estimated annual bottleneck cost: ${money(r.annualCost)}.<p class="eco-disclaimer">Time cost only; excludes sales, quality, delay, and downstream effects.</p>`,'eco-safe');track('bottleneck');}catch(e){set('b_result',e.message);}}
  function barfeed(){try{const r=M.barfeed({barLength:num('bf_bar'),partLength:num('bf_part'),remnant:num('bf_remnant'),cutoff:num('bf_kerf'),cycleSeconds:num('bf_cycle'),runHours:num('bf_hours'),efficiencyPercent:num('bf_eff')});set('bf_result',`<strong>${fmt(r.partsPerBar,0)} parts/bar</strong><br>${fmt(r.partsPerHour,1)} parts/hour; ${fmt(r.runParts,0)} parts in the run window.<p class="eco-disclaimer">Verify end loss, cutoff, restart loss, inspection, tool life, and unattended-run rules.</p>`,'eco-safe');track('barfeed');}catch(e){set('bf_result',e.message);}}
  function pressfeed(){try{const r=M.pressfeed({strokesPerMinute:num('pf_spm'),feedPitchInches:num('pf_pitch'),scheduledHours:num('pf_hours'),efficiencyPercent:num('pf_eff'),usableCoilFeet:num('pf_coil')});set('pf_result',`<strong>${fmt(r.goodStrokes,0)} theoretical good strokes</strong><br>${fmt(r.stripFeet,0)} feet of strip.${r.coilEquivalents?` ${fmt(r.coilEquivalents,2)} coil equivalents.`:''}<p class="eco-disclaimer">Validate die, feeder, stock, press rating, setup, scrap, guarding, and controls.</p>`,'eco-safe');track('pressfeed');}catch(e){set('pf_result',e.message);}}
  function quote(){const boxes=Array.from(document.querySelectorAll('[data-quote-check]')),checked=boxes.filter(x=>x.checked).length,score=Math.round(checked/boxes.length*100),missing=boxes.filter(x=>!x.checked).map(x=>x.value);set('q_result',`<strong>${score}% completeness</strong><br>${missing.length?`Missing: ${missing.join(', ')}.`:'All categories marked present.'}<p class="eco-disclaimer">Completeness does not confirm technical correctness, safety, capacity, or supplier capability.</p>`,score===100?'eco-safe':'');track('quote');}
  function score(kind,id,label){const r=M.score(Array.from(document.querySelectorAll(`[data-score="${kind}"]`)).map(x=>Number(x.value)));set(id,`<strong>${label}: ${r.percent}%</strong><br>${r.percent>=80?'Strong starting condition':r.percent>=60?'Usable with focused corrections':r.percent>=40?'Material gaps need action':'High-risk starting condition'}.<p class="eco-disclaimer">Self-assessment only; not a safety or readiness certification.</p>`,r.percent>=80?'eco-safe':'');track(kind);}
  function download(filename,rows){const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
  window.H38Tools={machining,payback,bottleneck,barfeed,pressfeed,quote,shopFlow:()=>score('shop-flow','sf_result','Shop flow score'),robot:()=>score('robot','rr_result','Robot-tending readiness'),downloadQuote:()=>download('h38-vendor-quote-completeness.csv',[['Category','Present','Notes'],['Scope and part definition','',''],['Volumes and mix','',''],['Cycle-time basis','',''],['Quality and inspection','',''],['Tooling and fixtures','',''],['Controls and interfaces','',''],['Safety and guarding responsibilities','',''],['Installation and training','',''],['Acceptance criteria','',''],['Lead time and warranty','',''],['Commercial exclusions','','']]),downloadScope:()=>download('h38-project-scope-builder.csv',[['Section','Answer'],['Desired finished outcome',''],['Current problem',''],['Boundary',''],['Known dimensions/data',''],['Constraints',''],['Files available',''],['Budget',''],['Timing',''],['Approvals required',''],['Open decisions','']])};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render,{once:true});else render();
})();
