(function(){
  'use strict';
  window.H38_PUBLIC_PROOF = Object.freeze({
    schemaVersion:1,
    release:'proof-evidence-system-2026-07-12',
    publicationPolicy:'Only explicitly public-safe summaries are included. Raw messages, attachments, addresses, people, customers, vendors, employees, employers, programs, drawings, pricing, and production data are excluded.',
    items:[
      {id:'CASE-MFG-001',title:'Blanking-feed automation planning',classification:'Anonymized reconstruction',domain:'Manufacturing and automation',summary:'A controlled reconstruction covering sequence definition, material handling, sensor logic, guarding questions, installation gates, and measurable production criteria without employer, vendor, part, or plant identifiers.',evidenceStatus:'Source records located; historical claim not upgraded.',privacyStatus:'PUBLIC_SAFE',sourceCount:0,relatedProducts:['H38-P010','H38-P011'],boundary:'Reconstruction only; no proprietary source drawings, programs, production values, vendor identity, or safety certification.'},
      {id:'CASE-MFG-002',title:'Robot-tended lathe workflow',classification:'Anonymized reconstruction',domain:'Manufacturing and automation',summary:'A public-safe reconstruction of part presentation, gripper and chuck interface questions, machine signals, probing, exception handling, queue control, and decision criteria.',evidenceStatus:'Source records located; exact machine and chronology remain private review items.',privacyStatus:'PUBLIC_SAFE',sourceCount:0,relatedProducts:['H38-P010','H38-P015'],boundary:'No machine serials, proprietary programs, part identities, videos, cycle data, or vendor-specific controls are published.'},
      {id:'CASE-MFG-004',title:'CNC and CAD/CAM standardization',classification:'Verified historical',domain:'Machining and digital manufacturing',summary:'Long-term experience implementing CNC programming standards, CAD/CAM workflows, posts, tool libraries, feeds and speeds, troubleshooting, quoting, and repeatable output controls.',evidenceStatus:'Public-safe work-history corroboration; quantitative claims remain on hold.',privacyStatus:'PUBLIC_SAFE',sourceCount:1,relatedProducts:['H38-P010','H38-P011'],boundary:'Public wording remains non-quantified until program-count and output claims are independently corroborated.'},
      {id:'CASE-RES-003',title:'Kitchen planning and sequence',classification:'Demonstration sample',domain:'Residential planning',summary:'A public-safe planning example covering use zones, fixed constraints, measurements, material decisions, and the order in which owner choices should be resolved.',evidenceStatus:'Purpose-built demonstration.',privacyStatus:'PUBLIC_SAFE',sourceCount:1,relatedProducts:['H38-P002','H38-P003'],boundary:'Demonstration structure only; not a permit, code, electrical, plumbing, or construction drawing.'},
      {id:'CASE-RES-004',title:'Garage flow and zone planning',classification:'Demonstration sample',domain:'Residential and shop planning',summary:'A 28-by-40-foot garage example showing protected vehicle lanes, workbench and tool zones, fixed-obstacle checks, missing measurements, and phased setup actions.',evidenceStatus:'Purpose-built hypothetical demonstration.',privacyStatus:'PUBLIC_SAFE',sourceCount:1,relatedProducts:['H38-P002','H38-P003','H38-P004'],boundary:'Not customer work, permit drawings, engineering, or field-verified dimensions.'},
      {id:'CASE-BIZ-001',title:'Small-business lead-to-job control',classification:'Demonstration sample',domain:'Business systems',summary:'A seven-status owner-controlled workflow connecting intake, missing information, quote review, scheduling, completion, and follow-up without automatic customer sends.',evidenceStatus:'Synthetic records only.',privacyStatus:'PUBLIC_SAFE',sourceCount:1,relatedProducts:['H38-P005','H38-P007','H38-P008'],boundary:'No real customer or communication data.'}
    ]
  });
})();
