/** Synthetic full-system fixtures. Requires explicit confirmation, TEST mode, and installed sheets. */
function h38PortalLoadSyntheticFixtures(confirmation){
  h38PortalAssertOwner_();
  if(confirmation!=='LOAD SYNTHETIC TEST RECORDS')throw new Error('TEST FIXTURE HOLD — exact confirmation required.');
  if(!H38_PORTAL_NEXT.TEST_MODE)throw new Error('TEST FIXTURE HOLD — test mode must be enabled.');
  if(!h38PortalInstalledStatus_().installed)throw new Error('TEST FIXTURE HOLD — install candidate sheets first.');
  var suffix=Utilities.getUuid().slice(0,6).toUpperCase(),today=h38PortalToday_();
  var customer=h38PortalSave('customers',{'Customer ID':'TEST-CUST-'+suffix,'Name':'Test Customer '+suffix,'Business':'Synthetic Test Shop','Email':'test+'+suffix.toLowerCase()+'@example.invalid','Phone':'000-000-0000','Preferred Contact':'Email','Lead Source':'Synthetic fixture','First Contact Date':today,'Customer Status':'Active','Privacy Classification':'Synthetic / No Customer Data','Notes':'Non-customer fixture only.'});
  var lead=h38PortalSave('leads',{'Lead ID':'TEST-LEAD-'+suffix,'Customer ID':customer['Customer ID'],'Name':customer.Name,'Business':customer.Business,'Email':customer.Email,'Phone':customer.Phone,'Preferred Contact':'Email','Lead Source':'Synthetic fixture','First Contact Date':today,'Status':'Qualified','Product / Bundle ID':'H38-P001','Next Action':'Review synthetic request','Privacy Classification':'Synthetic / No Customer Data','Notes':'Test fixture.'});
  var job=h38PortalSave('jobs',{'Job ID':'TEST-JOB-'+suffix,'Customer ID':customer['Customer ID'],'Customer Name':customer.Name,'Product / Bundle ID':'H38-P001','Scope':'Synthetic integrated business OS test','Inputs Received':'Synthetic notes','Intake Complete':'Yes','Payment Requirement':'Test only','Payment Status':'Partially paid','Start Authorization':'HOLD','Job Stage':'Owner review','Revision Allowance':'Test','Revision Status':'Not started','Due Date':today,'QA Status':'Needs review','Approval Status':'Rick Review Required / Owner Approval Required','Final Delivery Status':'Do Not Deliver','Revenue':100,'Expense Total':5,'Profit Estimate':95,'Notes':'No customer data and no external action.'});
  var quote=h38PortalSave('quotes',{'Quote ID':'TEST-QUOTE-'+suffix,'Job ID':job['Job ID'],'Customer ID':customer['Customer ID'],'Product / Bundle ID':'H38-P001','Catalog Price':100,'Quoted Amount':100,'Scope':'Synthetic scope','Payment Terms':'Test only','Turnaround':'Test','Revision Allowance':'Test','Status':'Approved','Approval Status':'Approved by Rick - Action Allowed','Rick Decision':'APPROVE QUOTE SEND','Notes':'Synthetic quote; do not send.'});
  var invoice=h38PortalSave('invoices',{'Invoice ID':'TEST-INV-'+suffix,'Job ID':job['Job ID'],'Customer ID':customer['Customer ID'],'Quote ID':quote['Quote ID'],'Invoice Type':'Synthetic invoice','Subtotal':100,'Discount':0,'Tax':0,'Fees':0,'Total':100,'Amount Paid':25,'Balance':75,'Due Date':today,'Status':'Partially paid','Approval Status':'Approved by Rick - Action Allowed','Rick Decision':'APPROVE INVOICE SEND','Payment Provider':'Manual test','Notes':'Synthetic invoice; no request sent.'});
  var payment=h38PortalSave('payments',{'Payment ID':'TEST-PAY-'+suffix,'Invoice ID':invoice['Invoice ID'],'Job ID':job['Job ID'],'Customer ID':customer['Customer ID'],'Payment Date':today,'Amount':25,'Payment Method':'Synthetic','Transaction Reference':'TEST','Status':'Paid','Recorded By':'Test fixture','Notes':'No live payment.'});
  var expense=h38PortalSave('expenses',{'Expense ID':'TEST-EXP-'+suffix,'Date':today,'Vendor':'Synthetic Vendor','Description':'Synthetic expense','Category':'Software','Amount':5,'Tax':0,'Payment Method':'Synthetic','Customer ID':customer['Customer ID'],'Job ID':job['Job ID'],'Product / Bundle ID':'H38-P001','Billable':'No','Reimbursable':'No','Recurring':'No','Accounting Status':'Recorded','Notes':'No live expense.'});
  var communication=h38PortalSave('communications',{'Communication ID':'TEST-COMM-'+suffix,'Customer ID':customer['Customer ID'],'Job ID':job['Job ID'],'Quote ID':quote['Quote ID'],'Invoice ID':invoice['Invoice ID'],'Category':'Synthetic email','Channel':'Email','Direction':'Outbound','Recipient':customer.Email,'Subject':'Synthetic test','Status':'Draft','Approval Status':'Rick Review Required / Owner Approval Required','Rick Decision':'HOLD','Notes':'No email sent.'});
  var social=h38PortalSave('social',{'Social ID':'TEST-SOC-'+suffix,'Campaign ID':'TEST-CAMP-'+suffix,'Product / Bundle ID':'H38-P001','Platform':'Test Platform','Content Type':'Synthetic','Caption':'Synthetic post','Status':'Draft','Approval Status':'Rick Review Required / Owner Approval Required','Rick Decision':'HOLD','Notes':'No publication.'});
  var advertising=h38PortalSave('advertising',{'Campaign ID':'TEST-CAMP-'+suffix,'Platform':'Test Ads','Product / Bundle ID':'H38-P001','Audience':'Synthetic','Location':'Test','Budget':10,'Start Date':today,'End Date':today,'Copy':'Synthetic ad','Status':'Draft','Approval Status':'Rick Review Required / Owner Approval Required','Rick Decision':'HOLD','Spend':0,'Leads':0,'Revenue':0,'Return Estimate':0,'Notes':'No launch or spend.'});
  var website=h38PortalSave('website',{'Change ID':'TEST-WEB-'+suffix,'Page':'Synthetic page','Change Type':'Test','Requested Change':'Synthetic change','Reason':'Integrated test','Before State':'Test','Proposed State':'Test','Files Affected':'none','Test Results':'Synthetic pass','Status':'Needs review','Approval Status':'Rick Review Required / Owner Approval Required','Rick Decision':'HOLD','Notes':'Job '+job['Job ID']+'; no merge or deployment.'});
  var calendar=h38PortalSave('calendar',{'Event ID':'TEST-EVENT-'+suffix,'Title':'Synthetic job review','Event Type':'Internal test','Related ID':job['Job ID'],'Start Time':h38PortalNow_(),'Product / Bundle ID':'H38-P001','Status':'Scheduled','Approval Warning':'Internal only','Conflict Warning':'None','Notes':'No external calendar action.'});
  var task=h38PortalSave('tasks',{'Task ID':'TEST-TASK-'+suffix,'Task Title':'Review synthetic integrated workspace','Task Type':'Job control','Related Customer ID':customer['Customer ID'],'Related Project':'Synthetic Test Shop','Job ID':job['Job ID'],'Product / Bundle ID':'H38-P001','Priority':'High','Due Date':today,'Status':'Needs review','Approval Requirement':'Rick Review Required / Owner Approval Required','Approval Status':'Rick Review Required / Owner Approval Required','Rick Decision':'HOLD','Assigned Action':'REVIEW_JOB','Source System':'Synthetic fixture','Source Sheet':'Portal Jobs','Source Row':job._rowNumber,'Last Update':h38PortalNow_(),'Next Recommended Action':'Open the full workspace and verify all linked sections.','Notes':'No external action.'});
  h38PortalWriteProof_({jobId:job['Job ID'],source:'Portal Test Fixtures',action:'Load integrated synthetic fixtures',decision:confirmation,result:'PASS',evidence:'Task='+task['Task ID']+' Job='+job['Job ID'],notes:'All modules linked with synthetic example.invalid data. No external action.'});
  return {status:'PASS',customer:customer,lead:lead,job:job,quote:quote,invoice:invoice,payment:payment,expense:expense,communication:communication,social:social,advertising:advertising,website:website,calendar:calendar,task:task,workspace:h38PortalWorkspace(task['Task ID'])};
}
